INSERT INTO OFFER VALUES (1,CURRENT_TIMESTAMP(),'Electronics-Mobile',8,CURRENT_());  
INSERT INTO OFFER VALUES (2,CURRENT_TIMESTAMP(),'Lotion',10,CURRENT_TIMESTAMP());
INSERT INTO OFFER VALUES (3,CURRENT_TIMESTAMP(),'Powder',20,CURRENT_TIMESTAMP());
INSERT INTO OFFER VALUES (4,CURRENT_TIMESTAMP(),'Electronics-Mobile',20,CURRENT_TIMESTAMP()); 
INSERT INTO OFFER VALUES (5,CURRENT_TIMESTAMP(),'Electronics-Washing Machine',20,CURRENT_TIMESTAMP()); 
INSERT INTO OFFER VALUES (6,CURRENT_TIMESTAMP(),'Electronics-TV',20,CURRENT_TIMESTAMP()); 