INSERT INTO OFFER VALUES (12,CURRENT_TIMESTAMP(),'Electronics',120,CURRENT_TIMESTAMP());  
INSERT INTO OFFER VALUES (13,CURRENT_TIMESTAMP(),'Electronics',100,CURRENT_TIMESTAMP());
INSERT INTO OFFER VALUES (14,CURRENT_TIMESTAMP(),'Electronics',100,CURRENT_TIMESTAMP()); 