DROP TABLE IF EXISTS OFFER;  
CREATE TABLE OFFER (  
OFFERID INT AUTO_INCREMENT  PRIMARY KEY,  
OFFER_PERCENTAGE FLOAT(8) NOT NULL,
OFFER_CATEGORY VARCHAR(255) NOT NULL,
VALID_FROM DATE NOT NULL,
VALID_UPTO DATE NOT NULL
);  